<% Dim breadcrumb 
breadcrumb = "Bank of America | Careers | "


Set page_titles  = Server.CreateObject("Scripting.Dictionary")
	
	' LINES OF BUSINESS SECTION
	'mpage
	page_titles.add "lob", "Lines of Business"
	'spage
	page_titles.add "lob_mortgagecareers", "Mortgage Careers"
	page_titles.add "lobgto", "Global Technology &amp; Operations"
	page_titles.add "lobgcsbb", "Global Consumer &amp; Small Business Banking"
	page_titles.add "lobgbmwm", "Global Banking, Markets and Wealth &amp; Investment Management"
	page_titles.add "lobcss", "Corporate Staff &amp; Support"
	page_titles.add "lobcfo", "Corporate Financial Operations"
	'tpage
	page_titles.add "lobbcc", "Banking Center Channel/Consumer Banking"
	page_titles.add "lobcf", "CFO Group/Finance"
	page_titles.add "lobfa", "Financial Advisor"
	page_titles.add "lobfaamericas", "Americas"
	page_titles.add "lobfaamericasrole", "Americas - Financial Advisor Role"
	page_titles.add "lobfaasia", "Asia Pacific"
	page_titles.add "lobfaasiarole", "Asia Pacific - Private Wealth Manager Role"
	page_titles.add "lobfaemea", "Europe, Middle East and Africa"
	page_titles.add "lobfaemearole", "Europe, Middle East and Africa - Financial Advisor Role"
	page_titles.add "lobgcb", "Global Commercial Banking"
	page_titles.add "lobgcib", "Global Banking &amp; Markets"
	page_titles.add "lobghr", "Corporate Staff &amp; Support | Global Human Resources"
	page_titles.add "lobgmca", "Global Marketing &amp; Corporate Affairs"
	page_titles.add "lobgr", "Risk Management"
	page_titles.add "lobgwim", "Global Wealth &amp; Investment Management"
	page_titles.add "lobnbcc", "Non-Banking Center Channel/Customer Care"
	page_titles.add "lob_fulfilment", "Fulfillment"
	page_titles.add "lob_homeequity", "Home Equity"
	page_titles.add "lob_insurance", "Insurance"
	page_titles.add "lob_locations", "Locations"
	page_titles.add "lob_mortgagesales", "Mortgage Sales"
	page_titles.add "lob_servicing", "Servicing"
	
	
	' LOCATIONS AND RELATED INFORMATION SECTION
	page_titles.add "locations", "Locations"
	page_titles.add "united_states", "United States"
	
	page_titles.add "awards", "Awards and recognition"
	page_titles.add "benefits", "Benefits &amp; Other Programs"
	page_titles.add "benefitsadv", "Benefits and Advantages"
	page_titles.add "career_compass", "Career Compass"
	page_titles.add "collrecruiting", "Campus Recruiting"
	page_titles.add "corpinfo", "Corporate Information"
	page_titles.add "corppartn", "Corporate Partnerships"
	page_titles.add "diversity", "Diversity and inclusion"
	page_titles.add "diversity_video", "Global Diversity &amp; Inclusion Video"
	page_titles.add "factsheets", "Fact Sheets"
	page_titles.add "flexibleworkarrangements", "Flexible Work Arrangements"
	page_titles.add "globalloc", "Global Locations"
	page_titles.add "homeloans", "Home Loans"
	page_titles.add "information_for_parents", "Information for parents"
	page_titles.add "insurance", "Health &amp; Insurance Benefits"
	page_titles.add "internships_details", "Internship Program Details"
	page_titles.add "internships", "Internships"
	page_titles.add "lifemanagement", "Life Management Benefits"
	page_titles.add "lifeworks", "LifeWorks &reg;"
	page_titles.add "majormarketlife", "Life in our Major Markets"
	page_titles.add "metlifeautohomeinsurance", "MetLife Auto & Home Insurance Program"
	page_titles.add "military_veteran_recruiting", "Military &amp; veteran recruiting"
	page_titles.add "mywork", "My Work &reg;"
	page_titles.add "otherprograms", "Other Programs: Your Finances, Community Commitments, and Education"
	page_titles.add "recruitingevents", "Recruiting events"
	page_titles.add "resume_interview_tips", "Resume &amp; interview tips"
	page_titles.add "retirement", "Retirement Benefits"
	page_titles.add "staffingprocess", "Staffing Process"
	page_titles.add "timeoff", "Time Away"
	
	page_titles.add "graduate", "Graduate/Associate Programs"
	page_titles.add "graduate_programs", "Graduate Programs/Associate Programs"
	page_titles.add "gp_bccmmldp", "Banking Center Channel Market Manager Leader Development Program"
	page_titles.add "gp_cc", "Compensation Consultant"
	page_titles.add "gp_cwsa", "Corporate Workplace Senior Analyst"
	page_titles.add "gp_dpsa", "Corporate Debt Products Associate"
	page_titles.add "gp_g", "TRUST OFFICER, U.S. Trust, Bank of America Private Wealth Management"
	page_titles.add "gp_gcsbbd", "Global Consumer and Small Business Banking Product Leader Development Program"
	page_titles.add "gp_iditd", "Instructional Designer"
	page_titles.add "gp_lc", "Learning Consultant"
	page_titles.add "gp_ldc", "Leadership Development Consultant"
	page_titles.add "gp_qpc", "Quality and Productivity Consultant"
	page_titles.add "gp_sflrp", "Operations MBA Program"
	page_titles.add "gp_sosaa", "Staffing Operations - Selection and Assessment Analyst"
	page_titles.add "gp_tmbap", "Technology MBA Program"
	page_titles.add "gp_wpa", "Staffing Operations - Workforce Planning Analyst"
	
	page_titles.add "internships_program", "Internship Programs"
	page_titles.add "ip_bccmmld", "Banking Center Channel Market Manager MBA Leader Development Intern"
	page_titles.add "ip_ca", "Corporate Audit Internship"
	page_titles.add "ip_cc", "Compensation Consultant Internship"
	page_titles.add "ip_cf", "Finance Intern Program"
	page_titles.add "ip_ci", "Corporate Investments Intern"
	page_titles.add "ip_cs", "Corporate Security Internship"
	page_titles.add "ip_ct", "Corporate Treasury Associate Program (CTAP)"
	page_titles.add "ip_cwa", "Corporate Workplace Analyst Internship"
	page_titles.add "ip_cwsa", "Corporate Workplace Senior Analyst Internship"
	page_titles.add "ip_dpa", "Corporate Debt Products Analyst Internship"
	page_titles.add "ip_dpsa", "Corporate Debt Products Associate Internship"
	page_titles.add "ip_gcsbbp", "Global Consumer and Small Business Banking Product Intern"
	page_titles.add "ip_gmca", "Global Marketing &amp; Corporate Affairs"
	page_titles.add "ip_gmgo", "Global Markets Group Operations Summer Analyst Program"
	page_titles.add "ip_gmo", "Global Middle Office Rotational Summer Analyst Program (GMO)"
	page_titles.add "ip_gmt", "Global Markets Technology Summer Analyst"
	page_titles.add "ip_gr", "Global Wealth &amp; Investment Management Graduate Internship Program"
	page_titles.add "ip_grmap", "Global Risk Management Associate Program (GRMAP) Intern"
	page_titles.add "ip_id", "Instructional Designer Intern"
	page_titles.add "ip_isbc", "Information Security Business Continuity Internship Opportunities"
	page_titles.add "ip_lc", "Learning Consultant Internship"
	page_titles.add "ip_ldc", "Leadership Development Consultant Intern"
	page_titles.add "ip_mr", "Markets Risk Associate Program (MRAP) Summer Intern"
	page_titles.add "ip_ncg", "Network Computing Group Internship Program"
	page_titles.add "ip_ncgmfb", "Network Computing Group Mainframe Build Intern Program"
	page_titles.add "ip_omap", "Operations Management Associate Program Intern"
	page_titles.add "ip_qpc", "Quality &amp; Productivity Consultant Internship"
	page_titles.add "ip_qpcas", "Quality &amp; Productivity Change Analyst Internship"
	page_titles.add "ip_scm", "Supply Chain Management Intern"
	page_titles.add "ip_sf", "Operations MBA Internship"
	page_titles.add "ip_so_saa", "Staffing Operations - Selection and Assessment Analyst Intern"
	page_titles.add "ip_so_wpa", "Staffing Operations - Workforce Planning, Process Design Analyst Intern"
	page_titles.add "ip_ss_cm", "Shared Services - Case Manager Internship"
	page_titles.add "ip_ss_wc", "Shared Services - Workforce Communications and Engagement Internship"
	page_titles.add "ip_tmba", "Technology MBA - Leadership Rotational Program"
	page_titles.add "ip_ungr", "Global Wealth &amp; Investment Management Undergraduate Internship Program"
	
	page_titles.add "undergraduate", "Undergraduate/Analyst Programs"
	page_titles.add "undergraduate_programs", "Undergraduate/Analyst Programs"
	page_titles.add "up_ca", "Corporate Audit"
	page_titles.add "up_cs", "Corporate Security"
	page_titles.add "up_ctap", "Corporate Treasury Associate Program"
	page_titles.add "up_cwa", "Corporate Workplace Analyst"
	page_titles.add "up_dpa", "Corporate Debt Products Analyst"
	page_titles.add "up_fmap", "Finance Management Associate Program"
	page_titles.add "up_gmgorp", "Global Markets Group Operations Rotational Program"
	page_titles.add "up_gmorp", "Global Middle Office Rotational Program"
	page_titles.add "up_gmt", "Global Markets Technology"
	page_titles.add "up_grmap", "Global Risk Management Associate Program"
	page_titles.add "up_gwimcr", "Global Wealth and Investment Management Compliance Risk"
	page_titles.add "up_isbc", "Information Security Business Continuity"
	page_titles.add "up_mrap", "Markets Risk Associate Program"
	page_titles.add "up_natorp", "North American Treasury Operations Rotational Program"
	page_titles.add "up_ncgldrp", "Network Computing Group Leadership Development Rotational Program"
	page_titles.add "up_ncgmbp", "Network Computing Group Mainframe Build Program"
	page_titles.add "up_qmap", "Quantitative Management Associate Program"
	page_titles.add "up_scmap", "Supply Chain Management Associate Program"
	page_titles.add "up_undergraduate", "Global Wealth & Investment Management - Undergraduate Opportunities"
	page_titles.add "values", "Values"
	page_titles.add "volunteergrants", "Volunteer Grants"
	page_titles.add "workforce", "Workforce Data"
	
	Dim breadcrumb_extended
	breadcrumb_extended = "Bank of America | Careers"
	
	If page_titles.Exists(mpage) Then breadcrumb_extended = breadcrumb_extended & " | " & page_titles.Item(mpage)
	If page_titles.Exists(spage) Then breadcrumb_extended = breadcrumb_extended & " | " & page_titles.Item(spage)
	If page_titles.Exists(tpage) Then breadcrumb_extended = breadcrumb_extended & " | " & page_titles.Item(tpage)
	If page_titles.Exists(fpage) Then breadcrumb_extended = breadcrumb_extended & " | " & page_titles.Item(fpage)
	If page_titles.Exists(fvpage) Then breadcrumb_extended = breadcrumb_extended & " | " & page_titles.Item(fvpage)
%>